### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by mstormi** [yozik04/vallox_websocket_api#1]
Hi,
just tried this on my Pi w/ Raspian Jessie, but failed, and I'm a Python n00b so no idea what to do.

pi@pi:~ $ /usr/bin/python -V
Python 2.7.9
pi@pi:~ $ cat x
#!/usr/bin/python

from vallox_websocket_api import Client

client = Client('192.168.178.26')
metrics = client.fetch_metrics()

from pprint import pprint
pprint(metrics)pi@pi:~ $ ./x
Traceback (most recent call last):
  File "./x", line 6, in <module>
    metrics = client.fetch_metrics()
  File "/usr/local/lib/python2.7/dist-packages/vallox_websocket_api/client.py", line 103, in fetch_metrics
    data = self._websocket_request(command=vlxDevConstants.WS_WEB_UI_COMMAND_READ_TABLES)
  File "/usr/local/lib/python2.7/dist-packages/vallox_websocket_api/client.py", line 93, in _websocket_request
    request = self._make_payload(command, dict)
  File "/usr/local/lib/python2.7/dist-packages/vallox_websocket_api/client.py", line 79, in _make_payload
    return numpy.array(arr, dtype=numpy.uint16).tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

**Comment by yozik04** [comment]
Hey,

You need to install numpy.

`$ pip install numpy`

**Comment by yozik04** [comment]
Or try to update your existing numpy

`$ pip install numpy --upgrade`

**Comment by mstormi** [comment]
Had to use --upgrade to get it to work (1h compile time !!). Thanks.
Do you happen to have any documentation of the modbus parameters and value ranges ?
Basically I'm looking for the names of the variables you see on a MV unit's web homepage.
And, most important, how to set the mode ? A_CYC_MODE ?

**Comment by yozik04** [comment]
Modbus parameters are in [constants.py](https://github.com/yozik04/vallox_websocket_api/blob/master/vallox_websocket_api/constants.py)

Sorry. I do not have any documentation because I reverse engineered their web api.

Setting mode is simple (copied from the index page):

`from vallox_websocket_api import Client

client = Client('192.168.9.106')
client.set_values({'A_CYC_STATE': 'C_CYC_STATE_HOME'})`

Variants are: C_CYC_STATE_HOME  | C_CYC_STATE_AWAY | C_CYC_STATE_BOOST

**Comment by mstormi** [comment]
FWIW, I found [this](https://www.vallox.com/files/1092/Modbus-instructions_ENG-250915.pdf)

**Comment by yozik04** [comment]
Thank you. Added the manual to the end of [README.md](../blob/master/README.md).
