### ISSUE TITLE
Using floats for target temperatures

### ISSUE THREAD

**Issue by Boulder08** [yozik04/vallox_websocket_api#11]
Is it possible to use floats for target temperatures? I tested sending some values to my Vallox Aito Kotilämpö, and fetching the metrics afterwards showed values rounded to xx.0.

**Comment by yozik04** [comment]
Internally inside the unit temperatures are stored in kelvin*10

**Comment by Boulder08** [comment]
I think you mean K*100? At least that's what the Modbus manual looks like, values between 27815..29815 are accepted.

Shouldn't it in that case be possible to use await client.set_values({'A_CYC_HOME_AIR_TEMP_TARGET': 21.5}) without the rounding occurring somewhere in the middle?

**Comment by yozik04** [comment]
Ahh, probably.

**Comment by yozik04** [comment]
Here is how I convert. No other rounding applied.
```python
def to_celcius(value):
    return round(value / 100.0 - 273.15, 1)


def to_kelvin(value):
    return int(value) * 100 + 27315
```

**Comment by yozik04** [comment]
`to_kelvin` rounds.

**Comment by Boulder08** [comment]
Yes, float(value) should do the trick?

**Comment by yozik04** [comment]
I'd do
```
def to_kelvin(value):
    return int(value * 10) * 10 + 27315
```

**Comment by Boulder08** [comment]
True, that would work also as we only need one decimal precision anyway..

**Comment by yozik04** [comment]
Ok, will commit in a minute.

**Comment by Boulder08** [comment]
Thank you :)

**Comment by yozik04** [comment]
Only one problem. Web UI of vallox's unit won't be able to show 0.1 precision temperatures.

**Comment by Boulder08** [comment]
I don't think that is an issue as long as you remember that when looking at the UI. The unit's own temperature display also chops off the float part but the read metrics then show the true values behind the scenes. I really don't know why they don't use more precise values in the display, there should be room for that.

**Comment by yozik04** [comment]
Probably because sensors have tolerance +-0.5 C

**Comment by Boulder08** [comment]
True. That's why I originally started wondering if it's possible to use floats as the documentation says the hysteresis of operation is 1C.

**Comment by yozik04** [comment]
Released
