### ISSUE TITLE
Compatibility with websockets 8.1?

### ISSUE THREAD

**Issue by bendavid** [yozik04/vallox_websocket_api#12]
Trying to reconcile some conflicting dependency issues in Home Assistant (see https://github.com/home-assistant/home-assistant/issues/31213#issuecomment-579379923) and it would simplify things moving forward if this library were compatible with websockets 8.1, in order to have compatible dependencies with the latest versions of discord.py and aiopylgtv.

**Comment by yozik04** [comment]
> Version 8.0 drops compatibility with Python 3.4 and 3.5.

Hmmm... Then it is time to drop 3.4 and 3.5. I will try to find time today or tomorrow.

**Comment by bendavid** [comment]
'websockets >= 7.0, < 9.0' would also be perfectly fine if that can work.

**Comment by yozik04** [comment]
Released in 2.4.0
