### ISSUE TITLE
Two new settable addresses

### ISSUE THREAD

**Issue by Boulder08** [yozik04/vallox_websocket_api#13]
A_CYC_EXTR_FAN_BALANCE_BASE and A_CYC_SUPP_FAN_BALANCE_BASE should be made settable, it's possible to read or write to them via Modbus. They affect the airflow balance.

**Comment by yozik04** [comment]
I am curious what is the use case?

**Comment by Boulder08** [comment]
Normally the airflow in my house is very close to balance, according to the measurements made when the device was installed. I'm then using my home automation script to check periodically if the heat recovery cell is in defrost state. If it is, I lower the amount of outdoor air intake slightly to reduce the amount of time it takes to defrost (because defrost is performed by bypassing the cell). Once the cell is back to heat recovery state, I set the values back to my defaults.

**Comment by yozik04** [comment]
Interesting. Thank you for sharing. I have added them. Released in 2.5.0
