### ISSUE TITLE
New Vallox software features?

### ISSUE THREAD

**Issue by Boulder08** [yozik04/vallox_websocket_api#14]
Are you able to locate also some new features introduced in Vallox MV 2.0? There's at least this one which is interesting, you can choose if the heat recovery cell can be bypassed or not. As an option, you can also enable a partial bypass (supported only by devices with a recent motherboard).

That general bypass disable would be very useful around this time of year. Sometimes it gets quite warm outside and the unit decides to bypass the recovery cell even though it's better to let the house gather heating energy for free during the day as the nights are cold. It would be better to control the feature in home automation instead of letting the unit decide what to do.

![image](https://user-images.githubusercontent.com/11799308/78656404-03c51600-78d0-11ea-98ea-fb6eab14ed24.png)

**Comment by yozik04** [comment]
I have not updated my unit to 2.0 yet. Does other functionality work well? Is it possible to downgrade back?

**Comment by Boulder08** [comment]
I've not had any issues with the new version (now at v2.0.2) in the unit itself, mine was updated automatically at the beginning of March. A nice addition was that the extra electric heaters can be controlled so I switched them off. There's also some control to activate them based on outdoor temperature.

They had some problems with cloud connections and the graphs in the web app but they have been fixed now. I don't know if it's possible to downgrade but I see no reason for that myself.

**Comment by yozik04** [comment]
> A nice addition was that the extra electric heaters can be controlled so I switched them off.

Wow. I definitely need that! Will upgrade in near days

**Comment by Boulder08** [comment]
Looks like this (don't know why I don't get an English GUI). I think the first one is the generic heater located after the recovery cell which can be controlled with the temperature slider (target temperature), and the other one is an extra heater.

![image](https://user-images.githubusercontent.com/11799308/78685120-fb81d080-78f9-11ea-8dea-c4f62cbc88ad.png)

**Comment by yozik04** [comment]
> Enable a partial bypass (supported only by devices with a recent motherboard)

Interesting how to distinguish if setting is supported for current model or not.
I've managed to get sw version and model from the unit. `get_info()`

**Comment by Boulder08** [comment]
I don't know if it's possible to tell which one supports that. I can only see the serial number and software version in the web app, maybe the serial number needs to be bigger than some value and then the unit has a motherboard supporting the feature. Then again, you can retrofit one of those on an older unit too, don't know if the serial number changes then.

I did test setting the partial bypass on and the unit just turned it off at some point so there's no harm done if you try to change the setting even if it's not supported.

**Comment by yozik04** [comment]
Ok. I have merged all new/renamed coil addresses from 2.0.2.

**Comment by yozik04** [comment]
Found some regressions on 2.0.2. It does use cell anymore when outside is hotter than inside. It was working perfectly fine in 1.x version.

**Comment by Boulder08** [comment]
> Found some regressions on 2.0.2. It does not use cell anymore when outside is hotter than inside. It was working perfectly fine in 1.x version.

Yes, I happened to notice the same thing just yesterday. I've now coded a workaround in my script to lock the cell bypass whenever the outside temperature minus one celsius is higher than the indoor temperature registered by the device.

I'll report it to Vallox as well, a lot of people are probably having the same issue :)

**Comment by yozik04** [comment]
I will probably have to do the same.

**Comment by Boulder08** [comment]
I got a response from Vallox and they are planning on releasing a new software version to fix the issue as soon as possible.

They told me that you can make it work with this procedure:
1) Enter the relay settings dialogue in Expert settings. Write down the current setting.
2) Set the relay to Duct radiator control.
3) Set the Duct radiator use method as 'Preheating'.
4) Set the relay setting back to what it was before.

**Comment by akoivist** [comment]
Thanks! That worked with my 145 MV.

**Comment by yozik04** [comment]
Just received same steps from them. Will see tomorrow if it has fixed the problem.

**Comment by yozik04** [comment]
Fixed for me as well.
