### ISSUE TITLE
Compatibility with `websockets` 10.1

### ISSUE THREAD

**Issue by cdce8p** [yozik04/vallox_websocket_api#17]
`websockets` is currently pinned to `<10.0`. Would it be possible to update it to `<11.0`? This would help resolve a potential dependency conflict in Home Assistant. https://websockets.readthedocs.io/en/stable/project/changelog.html#id2

Although `v10` drops support for Python 3.6, it wouldn't be necessary to do the same here. For Python 3.6 pip would just continue to install `v9`.
https://github.com/yozik04/vallox_websocket_api/blob/5c45be59e46bcd9cf9a14c92b4b1f48d86f38191/setup.py#L40

**Comment by yozik04** [comment]
Try 2.9.0 that I have just released =)

**Comment by cdce8p** [comment]
That works. Thanks for the quick fix!
