### ISSUE TITLE
Remove asynctest

### ISSUE THREAD

**Issue by fabaff** [yozik04/vallox_websocket_api#30]
`asyntest` is [unmaintained](https://github.com/Martiusweb/asynctest/issues/163) and has issues with Python 3.11. The tests should be migrated.

The first distributions which are shipping `vallox-websocket-api` are seeing build failures. This is problematic as it's a Home Assistant dependency.

**Comment by yozik04** [comment]
Will release a new version without asynctest, probably today.

**Comment by yozik04** [comment]
3.1.0 was released

**Comment by fabaff** [comment]
Thanks a lot.

Fixed with 10f7137b82b002bf2407d9883733da4f37d76e41
