### ISSUE TITLE
A new settable address

### ISSUE THREAD

**Issue by AspenLa** [yozik04/vallox_websocket_api#41]
Hi,

Can you make the 'A_CYC_SUPPLY_HEATING_ADJUST_MODE' settable address? 

Thanks!

**Comment by yozik04** [comment]
You need to verify if it will do what you want first. It is possible to make addresses settable in the integration code as well.

**Comment by AspenLa** [comment]
I´d like to change the heating adjust mode according to the outside and inside temperatures with my home automatin script. It´s possible to read or write to it via Modbus. They affect the airflow balance.

Unfortunately I haven't managed to make the address settable in the integration code.

**Comment by yozik04** [comment]
client.set_settable_address('A_CYC_REMAINING_TIME_FOR_FILTER', int)

From the readme

**Comment by AspenLa** [comment]
I know, red it. And it works. I'm trying to call the writing from the main script. The first one (set_state) works fine but the second does not:

class SetValues:

    def set_state(new_state:int):
        """ Sets the home or away mode \n 0 = home \n 1 = away
        """
        async def set_state():
            client = Client(clnt)
            await client.set_values({'A_CYC_STATE': new_state})
        asyncio.run(set_state())


    def set_heat_mode (new_mode:int):
        """ Sets the supply heating adjust mode. \n  0=supply heating \n 1=indoor constant control \n 2=indoor summer cooling mode"""
        #client = Client(clnt)
        #client.set_settable_address('A_CYC_SUPPLY_HEATING_ADJUST_MODE',int)
        async def run():
            client = Client(clnt)
            client.set_settable_address('A_CYC_SUPPLY_HEATING_ADJUST_MODE',int)
            await client.set_values({'A_CYC_SUPPLY_HEATING_ADJUST_MODE': 0})
        asyncio.run(run())

Any adwise?

**Comment by yozik04** [comment]
What exactly does not work? You see an exception?
