### ISSUE TITLE
Vallox becoming unavailable and sometimes shutting down - debug data

### ISSUE THREAD

**Issue by drawgas** [yozik04/vallox_websocket_api#56]
Related to https://github.com/home-assistant/core/issues/107636

As js is not supported for upload - uploading as txt
[bundle.txt](https://github.com/yozik04/vallox_websocket_api/files/13960492/bundle.txt)

**Comment by slovdahl** [comment]
If you want a 2.0.2 bundle too, here's mine: [bundle.txt](https://github.com/yozik04/vallox_websocket_api/files/13960524/bundle.txt)

**Comment by yozik04** [comment]
Added to tests in 35b975871457db27a5df6c1853dffe229206d112
Tests pass, so there should not be any issues with parsing js files.
