### ISSUE TITLE
Set filter change date

### ISSUE THREAD

**Issue by ElVit** [yozik04/vallox_websocket_api#57]
Hi I don't know if this is the right place to ask. 
I have a ValloPlus 180 MV and using Home Assistant to control it. 
You write a very nice integration and I'm very happy with it. 
Thank you!

But one thing I'm still missing here: it would be great if it is possible to change the date of the last filter change. 
(At least on the Web UI of Vallox it is possible to set the date)

So either an input_datetime entity to set the date manually in Home Assistant. 
Or even better: a button which will set the current date to the last filter changed date. 
Is this possible?

**Comment by yozik04** [comment]
=) Ohh, lazy people. You can do that from unit's control panel. At least this is how I do =)
I promise, I will think about it.

**Comment by ElVit** [comment]
I have no control unit 😐
I control my Ventilation system only trough the web page or Home Assistant 😃

**Comment by PhillyGilly** [comment]
I have a number of maintenance events in a dedicated calendar e.g. CH boiler service, MVHR filter change. This means that I can plan the jobs and get the materials ready. After the job is complete it would be neat to be able to write back to the Valox unit that the filters have been changed. I don't know if
```
 'A_CYC_FILTER_CHANGED_DAY': 23,
 'A_CYC_FILTER_CHANGED_MONTH': 3,
 'A_CYC_FILTER_CHANGED_YEAR': 17,
 'A_CYC_FILTER_CHANGE_INTERVAL': 120,
```
are writeable in this interface, but I would support @ElVit request to make them accessible from HA. Thanks

**Comment by PhillyGilly** [comment]
> Hi I don't know if this is the right place to ask. I have a ValloPlus 180 MV and using Home Assistant to control it. You write a very nice integration and I'm very happy with it. Thank you!
> 
> But one thing I'm still missing here: it would be great if it is possible to change the date of the last filter change. (At least on the Web UI of Vallox it is possible to set the date)
> 
> So either an input_datetime entity to set the date manually in Home Assistant. Or even better: a button which will set the current date to the last filter changed date. Is this possible?

If the date values are writable, then a push-button automation is trivial to script.
