### ISSUE TITLE
Settable value for: 'A_CYC_POST_HEATER_WINTER_SETPOINT'

### ISSUE THREAD

**Issue by jamisi** [yozik04/vallox_websocket_api#66]
Hi, 
Can you add value: 'A_CYC_POST_HEATER_WINTER_SETPOINT' as a settable?
I tried to use temporary way without success.
Thanks

**Comment by yozik04** [comment]
Just curious. What will you use it for?

**Comment by yozik04** [comment]
A_CYC_MLV_SUMMER_SETPOINT: 15.0
A_CYC_MLV_WINTER_SETPOINT: -5.0
A_CYC_POST_HEATER_WINTER_SETPOINT: 19.0

All these are temperatures. So previously we have read it wrong.

**Comment by jamisi** [comment]
Hello,

Thanks for the mail.

I use it in my automation for adjusting the heat exchanger bypass fuction.
At spring and autumm I would like to keep it higher and take all heat thru
exchanger even outdoor temperature is for example 18’C

At summer I adjust it lower (in automation)

Br
Jari

su 14.4.2024 klo 11.27 Jevgeni Kiski ***@***.***> kirjoitti:

**Comment by yozik04** [comment]
For that I use bypass lock. It is even exposed in HomeAssistant.

**Comment by yozik04** [comment]
Released in `5.2.0`
