### ISSUE TITLE
Problem setting working-mode / cannot import name 'PROFILE' from 'vallox_websocket_api'

### ISSUE THREAD

**Issue by juergen852** [yozik04/vallox_websocket_api#67]
I try to run the following python script 

import asyncio
from vallox_websocket_api import Vallox, PROFILE
client = Vallox('10.8.12.64') # Vallox unit IP
async def run():
    data = await client.fetch_metric_data()
    profile = data.profile # RETURNS a PROFILE.* value
    await client.set_profile(PROFILE.HOME) # Permanently HOME profile
asyncio.run(run())

**python --version** gives me Python 3.10.12

**Error-Message:**
$ python3 set-modus.py
Traceback (most recent call last):
  File "/......./set-modus.py", line 2, in <module>
    from vallox_websocket_api import Vallox, PROFILE
ImportError: cannot import name 'PROFILE' from 'vallox_websocket_api' (/home/jm/.local/lib/python3.10/site-packages/vallox_websocket_api/__init__.py)

What could be the cause?

**Comment by yozik04** [comment]
Wrong includes 😃

**Comment by juergen852** [comment]
Sorry.... Smile
As I am not so experienced to interpret "Wrong imports":.....

I deleted /home/jm/.local/lib/python3.10/site-packages/vallox_websocket_api/ and tried to reinstall.

**Reinstall**
jm@jm:~/Programme/valloxcontrols$ pip install vallox-websocket-api
Defaulting to user installation because normal site-packages is not writeable
Collecting vallox-websocket-api
  Downloading vallox_websocket_api-5.2.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 KB 1.1 MB/s eta 0:00:00
Requirement already satisfied: websockets>=9.1 in /home/jm/.local/lib/python3.10/site-packages (from vallox-websocket-api) (10.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.7.0 in /home/jm/.local/lib/python3.10/site-packages (from vallox-websocket-api) (3.9.5)
Requirement already satisfied: construct<3.0.0,>=2.9.0 in /home/jm/.local/lib/python3.10/site-packages (from vallox-websocket-api) (2.10.68)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (6.0.5)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (4.0.3)
Requirement already satisfied: frozenlist>=1.1.1 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (1.4.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (1.9.4)
Requirement already satisfied: attrs>=17.3.0 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (23.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in /home/jm/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (1.3.1)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.7.0->vallox-websocket-api) (3.3)
Installing collected packages: vallox-websocket-api
Successfully installed vallox-websocket-api-5.2.0

**Seems OK.**
$ python3 set-modus.py 
Traceback (most recent call last):
  File "/home/jm/Programme/valloxcontrols/set-modus.py", line 2, in <module>
    from vallox_websocket_api import Vallox, PROFILE
ImportError: cannot import name 'PROFILE' from 'vallox_websocket_api' (/home/jm/.local/lib/python3.10/site-packages/vallox_websocket_api/__init__.py)

**Contents of set-modus.py:**
import asyncio
from vallox_websocket_api import Vallox, PROFILE
client = Vallox('10.8.12.64') # Vallox unit IP

async def run():
    data = await client.fetch_metric_data()
    profile = data.profile # RETURNS a PROFILE.* value
    await client.set_profile(PROFILE.HOME) # Permanently HOME profile
    #await client.set_profile(PROFILE.AWAY) # Permanently AWAY profile
asyncio.run(run())

**python3 --version** gives me Python 3.10.12

All other examples (reading values, reading history, setting values) work.
Just client.set_profile causes problems....

**Comment by yozik04** [comment]
I have updated the example. `PROFILE` was wrong. `Profile` is correct.

**Comment by juergen852** [comment]
Perfect, Works !!
(I had tried ..."_api import Vallox, **Profile**"... but did not try "client.set_profile( **Profile.** HOME)..."
