### ISSUE TITLE
Not possible to add settable addresses

### ISSUE THREAD

**Issue by Boulder08** [yozik04/vallox_websocket_api#68]
I just updated my Python packages and now it is not possible to add new settable addresses. Possibly a problem between the module and some Python internals?

client.set_settable_address('A_CYC_HOME_RH_CTRL_ENABLED', int) is what I usually need, not sure of the others I've used in the past if they have changed from automatically enabled to disabled between module versions.

```
Traceback (most recent call last):
  File "C:\Daikin\Scripts\weatherstation.pyw", line 35, in <module>
    client.set_settable_address('A_CYC_REMAINING_TIME_FOR_FILTER', int)
  File "C:\Program Files\Python312\Lib\site-packages\vallox_websocket_api\client.py", line 180, in set_settable_address
    elif isinstance(address, str) and address in self.data_model.addresses:
  File "C:\Program Files\Python312\Lib\functools.py", line 995, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python312\Lib\site-packages\vallox_websocket_api\data\model.py", line 33, in addresses
    assert self.constants, "No constants loaded"
AssertionError: No constants loaded
```

**Comment by yozik04** [comment]
You need to call
`await client.load_data_model()` before you will be able to call `client.set_settable_address('A_CYC_REMAINING_TIME_FOR_FILTER', int)`.

I made `A_CYC_FILTER_CHANGED_*` settable in some previous release. You'd better use these.

**Comment by Boulder08** [comment]
Thanks, with that call added into the script it works. You may want to put it in the readme where the settable address thing is mentioned.
