### ISSUE TITLE
set_settable_address('A_CYC_FAN_SPEED',5) >> Error

### ISSUE THREAD

**Issue by FloppyFlow** [yozik04/vallox_websocket_api#7]
Hey guys,
I want to set a value (e.g. the fan speed) and an error occurs:
AttributeError: Only float or int type are supported

My coding is like this:
`client.set_settable_address('A_CYC_FAN_SPEED', 5)
`
A look in the code shows up the following line:
```
def set_settable_address(self, address, var_type):
    if var_type not in [int, float]:
      raise AttributeError("Only float or int type are supported"
```

I pass the parameter '5' as an integer. But I think that this line isn't correct:
`if var_type not in [int, float]:`

var_type is the value, so it should be:
`if type(value).__name__ not in [int,float]:`

Just my 2 cents...

By the way: nice work. I really like this project and I want to use it!!!!

**Comment by yozik04** [comment]
`type(value).__name__` will produce string. I guess you meant `not in ['int','float']`. But anyway you did not understood the purpose of `set_settable_address` method. It is used to make a parameter settable if it is not settable yet.


In your case please use:
`client.set_values({'A_CYC_HOME_SPEED_SETTING': 5})`
`client.set_values({'A_CYC_AWAY_SPEED_SETTING': 5})`
`client.set_values({'A_CYC_BOOST_SPEED_SETTING': 5})`
