### ISSUE TITLE
download time series of measurements potentially stored on the unit

### ISSUE THREAD

**Issue by gunarka** [yozik04/vallox_websocket_api#8]
Hi, great api working out of the box for me (ValloPlus 270 MV)!

Via the Vallox webinterface time series of hourly sensor data (tempertures, humudity, CO2) can be plotted. Therefore I assume that the unit stores these information.

From my perspective it would be great to be able to retrieve these information via this api as well.

What do you think?

**Comment by timBeDev** [comment]
Would be nice indeed

**Comment by yozik04** [comment]
You can make CSV part yourself =)
See Readme update how to use it.

**Comment by yozik04** [comment]
Output format is currently probably bad. Sugestions?

**Comment by gunarka** [comment]
Issue raised, issue closed.
Man you are fast!  ...and it's working!
Seems the unit stores about two month of sensor readings.

Regarding the formatting: the output is already kind of a tag list. Therefore I will try to make it a proper XML at the weekend, by replacing some chars.

Will come back...

**Comment by yozik04** [comment]
I have modified format in 1.5.0

```
{
   'date': datetime.datetime(2019, 3, 29, 8, 23),
   'id': 5,
   'name': 'humidity',
   'value': 45
}
```

Should be released to pypa in some minutes.

**Comment by yozik04** [comment]
I'll keep the issue open for a while.

The unit clock drifts. Probably we need a function to set current date as well.
